services:
  db:
    build:
      context: .
      dockerfile: ./docker-build/database/Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: aml_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
